name: Build Mini FAIR Plugin ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up PHP ≥7.4
      - name: Set up PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '7.4'
          extensions: mbstring, json, xml

      # 3. Cache & install Composer (no-dev)
      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # 4. Zip plugin directory
      - name: Create plugin ZIP
        run: |
          PLUGIN_SLUG=mini-fair
          ZIP_NAME=${PLUGIN_SLUG}.zip
          zip -r $ZIP_NAME . \
            -x "*.git*" \
            -x ".github/*" \
            -x "tests/*" \
            -x ".gitignore" \
            -x ".gitattributes"

      # 5. Upload the ZIP as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-fair-plugin-zip
          path: mini-fair.zip
